import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateExecutiveReport = (stats, departments) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // Branding
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229); // Indigo
    doc.text("CNCS Executive Report", 14, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on: ${date}`, 14, 28);
    doc.text("Confidential - Internal Use Only", 14, 34);

    // Line
    doc.setDrawColor(200);
    doc.line(14, 38, 196, 38);

    // Executive Summary
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Executive Summary", 14, 50);

    doc.setFontSize(11);
    doc.text(`Total Instructors: ${stats.totalInstructors}`, 14, 60);
    doc.text(`Avg Rating: ${stats.avgRating} / 5.0`, 14, 66);
    doc.text(`Engagement (Mo): ${stats.engagementThisMonth}`, 14, 72);
    doc.text(`Total Departments: ${stats.totalDepartments}`, 14, 78);

    // Departments Table
    doc.setFontSize(16);
    doc.text("Department Performance", 14, 95);

    // Headers
    let y = 105;
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Department", 14, y);
    doc.text("Instructors", 80, y);
    doc.text("Rating", 120, y);
    doc.text("Sentiment", 160, y);
    
    // Rows
    doc.setTextColor(0);
    y += 8;
    departments.forEach(dept => {
        doc.text(dept.name, 14, y);
        doc.text(String(dept.instructorCount), 80, y);
        doc.text(String(dept.rating), 120, y);
        doc.text(dept.sentiment, 160, y);
        y += 8;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by RYCNCSI Management Portal", 14, 290);

    doc.save(`CNCS_Executive_Report_${date.replace(/\//g, '-')}.pdf`);
};

export const generateInstructorReport = (profile, stats, feedback) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // 1. Header & Branding
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setFontSize(24);
    doc.setTextColor(255, 255, 255);
    doc.text("Instructor Performance Report", 14, 20);
    
    doc.setFontSize(10);
    doc.text(`Generated: ${date} | Confidential`, 14, 32);

    // 2. Profile Summary (Y: 50)
    doc.setTextColor(50);
    doc.setFontSize(14);
    doc.text(`Instructor: ${profile?.fullName || 'N/A'}`, 14, 55);
    doc.setFontSize(10);
    doc.text(`Department: ${profile?.department || 'General'}`, 14, 62);
    doc.text(`Report ID: #${Math.floor(Math.random() * 10000)}`, 14, 68);

    // 3. Key Metrics Grid (Y: 80)
    doc.setDrawColor(200);
    doc.line(14, 75, 196, 75);

    const statsY = 90;
    // Box 1: Avg Rating
    doc.setFontSize(12); doc.setTextColor(100); doc.text("Avg Rating", 14, statsY);
    doc.setFontSize(20); doc.setTextColor(0); doc.text(String(stats?.avgRating || "0.0"), 14, statsY + 10);
    
    // Box 2: Total Reviews
    doc.setFontSize(12); doc.setTextColor(100); doc.text("Total Reviews", 60, statsY);
    doc.setFontSize(20); doc.setTextColor(0); doc.text(String(stats?.reviewCount || "0"), 60, statsY + 10);

    // Box 3: Students
    doc.setFontSize(12); doc.setTextColor(100); doc.text("Students", 110, statsY);
    doc.setFontSize(20); doc.setTextColor(0); doc.text(String(stats?.totalStudents || "0"), 110, statsY + 10);

    // Box 4: Courses
    doc.setFontSize(12); doc.setTextColor(100); doc.text("Courses", 160, statsY);
    doc.setFontSize(20); doc.setTextColor(0); doc.text(String(stats?.courseCount || "0"), 160, statsY + 10);

    // 4. Recent Feedback Table
    let y = 120;
    doc.setFontSize(14);
    doc.setTextColor(79, 70, 229);
    doc.text("Recent Student Feedback", 14, y);
    
    y += 10;
    const tableData = feedback?.slice(0, 10).map(f => [
        f.courseCode || 'N/A',
        new Date(f.timestamp || Date.now()).toLocaleDateString(),
        f.rating ? `${f.rating} ★` : '-',
        f.comment?.substring(0, 40) + '...' || 'No comment'
    ]) || [];

    autoTable(doc, {
        startY: y,
        head: [['Course', 'Date', 'Rating', 'Comment']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229] },
        styles: { fontSize: 9 }
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount} - RYCNCSI System`, 105, 290, null, null, "center");
    }

    doc.save(`Instructor_Report_${profile?.fullName?.replace(/\s+/g, '_')}_${date.replace(/\//g, '-')}.pdf`);
};
