import jsPDF from 'jspdf';
import 'jspdf-autotable'; // Ensure this is installed or use manual positioning

export const generateExecutiveReport = (stats, departments) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // Branding
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229); // Indigo
    doc.text("CNCS Executive Report", 14, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on: ${date}`, 14, 28);
    doc.text("Confidential - Internal Use Only", 14, 34);

    // Line
    doc.setDrawColor(200);
    doc.line(14, 38, 196, 38);

    // Executive Summary
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Executive Summary", 14, 50);

    doc.setFontSize(11);
    doc.text(`Total Instructors: ${stats.totalInstructors}`, 14, 60);
    doc.text(`Avg Rating: ${stats.avgRating} / 5.0`, 14, 66);
    doc.text(`Engagement (Mo): ${stats.engagementThisMonth}`, 14, 72);
    doc.text(`Total Departments: ${stats.totalDepartments}`, 14, 78);

    // Departments Table
    doc.setFontSize(16);
    doc.text("Department Performance", 14, 95);

    // Headers
    let y = 105;
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Department", 14, y);
    doc.text("Instructors", 80, y);
    doc.text("Rating", 120, y);
    doc.text("Sentiment", 160, y);
    
    // Rows
    doc.setTextColor(0);
    y += 8;
    departments.forEach(dept => {
        doc.text(dept.name, 14, y);
        doc.text(String(dept.instructorCount), 80, y);
        doc.text(String(dept.rating), 120, y);
        doc.text(dept.sentiment, 160, y);
        y += 8;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by RYCNCSI Management Portal", 14, 290);

    doc.save(`CNCS_Executive_Report_${date.replace(/\//g, '-')}.pdf`);
};
